fix: Only delete file when it exists
flutterchina/dio pull request #1393
Opened 2022-01-20 09:47 UTC by AlexV525

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: N/A

### Pull Request Description

Before we delete the downloading file, we should determine whether it exists.

2022-01-20 09:49 UTC, AlexV525 commented
/cc @wendux @kuhnroyal

2022-01-20 10:34 UTC, kuhnroyal commented
Nice, thanks! Can you fix the formatting and add a changelog entry please.

2022-01-20 10:59 UTC, AlexV525 commented
Should be good to go.

2022-01-20 14:32 UTC, kuhnroyal requested changes
We don't know yet what the next version will be. Just add the changes to the unreleased block.

2022-01-20 14:32 UTC, kuhnroyal commented on dio/CHANGELOG.md
> +# 4.0.5-beta2
```suggestion
```

2022-01-20 16:00 UTC, kuhnroyal approved these changes

2022-01-24 10:30 UTC, AlexV525 commented
Done with rebasing, squashing, and format update.

2022-01-24 10:40 UTC, kuhnroyal commented
Thank you!

2022-01-24 10:40 UTC, merged